services:
  app:
    build: ./functions
    ports:
      - "5001:5001"
    environment:
      - FIRESTORE_EMULATOR_HOST=firebase-emulator:8080
      - FIREBASE_AUTH_EMULATOR_HOST=firebase-emulator:9099
      - FIREBASE_STORAGE_EMULATOR_HOST=firebase-emulator:9199
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ENCRYPTION_KEY=$(openssl rand -hex 32)
      - USE_MAILHOG=true
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  
  mailhog:
        image: mailhog/mailhog:latest
        ports:
          - 1025:1025
          - 8025:8025

  firebase-emulator:
    image: node:22
    working_dir: /app
    volumes:
      - ./functions:/app
    command: sh -c "apt-get update && apt-get install -y openjdk-17-jre-headless && npm install -g firebase-tools && firebase emulators:start --only firestore,auth,storage --project thesis-dev-project"
    ports:
      - "8080:8080"   # Firestore
      - "9099:9099"   # Auth
      - "9199:9199"   # Storage
    environment:
      - FIRESTORE_EMULATOR_HOST=localhost:8080
      - FIREBASE_AUTH_EMULATOR_HOST=localhost:9099
      - FIREBASE_STORAGE_EMULATOR_HOST=localhost:9199